#!/usr/bin/python3

""" 
    Starter code for exploring the Enron dataset (emails + finances);
    loads up the dataset (pickled dict of dicts).

    The dataset has the form:
    enron_data["LASTNAME FIRSTNAME MIDDLEINITIAL"] = { features_dict }

    {features_dict} is a dictionary of features associated with that person.
    You should explore features_dict as part of the mini-project,
    but here's an example to get you started:

    enron_data["SKILLING JEFFREY K"]["bonus"] = 5600000
    
"""

import joblib

enron_data = joblib.load(open("/Users/kavanamanvi/Desktop/ALGO/ud120-projects-master/final_project/final_project_dataset.pkl", "rb"))

print(len(enron_data))

print(len(enron_data['METTS MARK']))


poi=0

for key,val in enron_data.items():
    if enron_data[key]["poi"]==True:
        poi+=1

print("poi: "+str(poi))


print(enron_data['PRENTICE JAMES']["total_stock_value"])

print(enron_data['COLWELL WESLEY']['from_this_person_to_poi'])


146
21
poi: 18
1095040
11
