#!/usr/bin/python3

""" 
    This is the code to accompany the Lesson 1 (Naive Bayes) mini-project. 

    Use a Naive Bayes Classifier to identify emails by their authors
    
    authors and labels:
    Sara has label 0
    Chris has label 1
"""
    
import sys
from time import time
sys.path.append("/Users/kavanamanvi/Desktop/Algo/ud120-projects/tools/")
from email_preprocess import preprocess

### features_train and features_test are the features for the training
### and testing datasets, respectively
### labels_train and labels_test are the corresponding item labels
features_train, features_test, labels_train, labels_test = preprocess()


##############################################################
# Enter Your Code Here

from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(features_train,labels_train)

from sklearn.metrics import accuracy_score
y_pred = clf.predict(features_test)

accuray=accuracy_score(labels_test, y_pred)
print("Accuracy: "+str(accuray))

##############################################################

##############################################################
'''
You Will be Required to record time for Training and Predicting 
The Code Given on Udacity Website is in Python-2
The Following Code is Python-3 version of the same code
'''

# t0 = time()
# # < your clf.fit() line of code >
# print("Training Time:", round(time()-t0, 3), "s")

# t0 = time()
# # < your clf.predict() line of code >
# print("Predicting Time:", round(time()-t0, 3), "s")

##############################################################



kavanamanvi@Kavanas-MacBook-Air ud120-projects % /usr/local/bin/python3 /Users/kavanamanvi/Desktop/Algo/ud120-projec
ts/naive_bayes/nb_author_id.py
No. of Chris training emails :  7936
No. of Sara training emails :  7884
Accuracy: 0.9732650739476678

